### ISSUE TITLE
categoria: portfólio

### ISSUE THREAD

**Issue by euotiniel** [angolaosc/aba#9]
Acho que seria interessante adicionar a categoria de portfólios ou websites incríveis feitos por angolanos.

**Comment by JesseIngles** [comment]
Acho uma excelente ideia! Adicionar uma categoria de portfólios e websites incríveis feitos por angolanos seria ótimo para destacar ainda mais o talento local. Vamos em frente com essa inclusão!

Sinta-se à vontade para começar!
